"use client";

import type { MotionParams } from "../types";

export function Aurora({ hueA, hueB, speed, intensity }: MotionParams) {
  const opacity = 0.25 + intensity * 0.45;
  return (
    <div className="absolute inset-0 overflow-hidden bg-[oklch(12%_0.01_285)]">
      <div
        className="absolute -top-1/4 left-[10%] h-[70%] w-[55%] rounded-full blur-[90px]"
        style={{
          background: `radial-gradient(ellipse, oklch(55% 0.22 ${hueA}) 0%, transparent 70%)`,
          opacity,
          animation: `aurora-a ${18 / speed}s ease-in-out infinite alternate`,
        }}
      />
      <div
        className="absolute right-[5%] -bottom-1/4 h-[75%] w-[60%] rounded-full blur-[100px]"
        style={{
          background: `radial-gradient(ellipse, oklch(60% 0.16 ${hueB}) 0%, transparent 70%)`,
          opacity: opacity * 0.8,
          animation: `aurora-b ${24 / speed}s ease-in-out infinite alternate`,
        }}
      />
      <div
        className="absolute top-[30%] left-[45%] h-[45%] w-[35%] rounded-full blur-[110px]"
        style={{
          background: `radial-gradient(circle, oklch(65% 0.18 ${(hueA + hueB) / 2}) 0%, transparent 70%)`,
          opacity: opacity * 0.5,
          animation: `aurora-a ${30 / speed}s ease-in-out infinite alternate-reverse`,
        }}
      />
      <style>{`
        @keyframes aurora-a {
          from { transform: translate(0,0) scale(1) rotate(0deg); }
          to { transform: translate(8%,12%) scale(1.2) rotate(12deg); }
        }
        @keyframes aurora-b {
          from { transform: translate(0,0) scale(1.1); }
          to { transform: translate(-10%,-8%) scale(0.9); }
        }
      `}</style>
    </div>
  );
}

export function auroraSource(p: MotionParams): string {
  return `"use client";

/** Aurora background — generated by NOCTURNE Motion Engine. */
export function AuroraBackground() {
  return (
    <div style={{ position: "absolute", inset: 0, overflow: "hidden", background: "oklch(12% 0.01 285)" }}>
      <div style={{ position: "absolute", top: "-25%", left: "10%", height: "70%", width: "55%", borderRadius: "50%", filter: "blur(90px)", background: "radial-gradient(ellipse, oklch(55% 0.22 ${p.hueA}) 0%, transparent 70%)", opacity: ${(0.25 + p.intensity * 0.45).toFixed(2)}, animation: "aurora-a ${(18 / p.speed).toFixed(1)}s ease-in-out infinite alternate" }} />
      <div style={{ position: "absolute", right: "5%", bottom: "-25%", height: "75%", width: "60%", borderRadius: "50%", filter: "blur(100px)", background: "radial-gradient(ellipse, oklch(60% 0.16 ${p.hueB}) 0%, transparent 70%)", opacity: ${((0.25 + p.intensity * 0.45) * 0.8).toFixed(2)}, animation: "aurora-b ${(24 / p.speed).toFixed(1)}s ease-in-out infinite alternate" }} />
      <style>{\`
        @keyframes aurora-a { from { transform: translate(0,0) scale(1) rotate(0deg); } to { transform: translate(8%,12%) scale(1.2) rotate(12deg); } }
        @keyframes aurora-b { from { transform: translate(0,0) scale(1.1); } to { transform: translate(-10%,-8%) scale(0.9); } }
      \`}</style>
    </div>
  );
}
`;
}
