"use client";

import { useEffect, useRef } from "react";
import type { MotionParams } from "../types";

export function HorizonGrid({ hueA, hueB, speed, intensity }: MotionParams) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let raf = 0;
    let t = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);

    function resize() {
      if (!canvas) return;
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    }
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    function frame() {
      if (!canvas || !ctx) return;
      const { width, height } = canvas;
      const horizon = height * 0.45;
      ctx.fillStyle = "oklch(11% 0.012 285)";
      ctx.fillRect(0, 0, width, height);
      t += 0.004 * speed;

      // Horizon glow
      const glow = ctx.createLinearGradient(0, horizon - 80 * dpr, 0, horizon + 60 * dpr);
      glow.addColorStop(0, "transparent");
      glow.addColorStop(0.5, `oklch(60% 0.2 ${hueA} / ${0.25 + intensity * 0.3})`);
      glow.addColorStop(1, "transparent");
      ctx.fillStyle = glow;
      ctx.fillRect(0, horizon - 80 * dpr, width, 140 * dpr);

      // Vertical lines converging on center
      const vCount = Math.floor(14 + intensity * 18);
      ctx.lineWidth = dpr;
      for (let i = -vCount; i <= vCount; i++) {
        const spread = (i / vCount) * width * 2.2;
        ctx.strokeStyle = `oklch(60% 0.16 ${hueB} / ${0.28 - Math.abs(i / vCount) * 0.18})`;
        ctx.beginPath();
        ctx.moveTo(width / 2 + spread * 0.06, horizon);
        ctx.lineTo(width / 2 + spread, height);
        ctx.stroke();
      }

      // Horizontal lines rolling toward viewer
      const hCount = 16;
      for (let i = 0; i < hCount; i++) {
        const z = ((i / hCount + t) % 1 + 1) % 1;
        const y = horizon + Math.pow(z, 2.4) * (height - horizon);
        ctx.strokeStyle = `oklch(65% 0.18 ${hueA} / ${z * 0.5})`;
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }
      raf = requestAnimationFrame(frame);
    }
    raf = requestAnimationFrame(frame);

    return () => {
      cancelAnimationFrame(raf);
      observer.disconnect();
    };
  }, [hueA, hueB, speed, intensity]);

  return <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" />;
}

export function horizonGridSource(p: MotionParams): string {
  return `"use client";

import { useEffect, useRef } from "react";

/** Horizon grid background — generated by NOCTURNE Motion Engine. */
export function HorizonGridBackground() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let raf = 0;
    let t = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);
    const resize = () => {
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    };
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    const frame = () => {
      const { width, height } = canvas;
      const horizon = height * 0.45;
      ctx.fillStyle = "oklch(11% 0.012 285)";
      ctx.fillRect(0, 0, width, height);
      t += ${(0.004 * p.speed).toFixed(4)};
      const glow = ctx.createLinearGradient(0, horizon - 80 * dpr, 0, horizon + 60 * dpr);
      glow.addColorStop(0, "transparent");
      glow.addColorStop(0.5, "oklch(60% 0.2 ${p.hueA} / ${(0.25 + p.intensity * 0.3).toFixed(2)})");
      glow.addColorStop(1, "transparent");
      ctx.fillStyle = glow;
      ctx.fillRect(0, horizon - 80 * dpr, width, 140 * dpr);
      const vCount = ${Math.floor(14 + p.intensity * 18)};
      ctx.lineWidth = dpr;
      for (let i = -vCount; i <= vCount; i++) {
        const spread = (i / vCount) * width * 2.2;
        ctx.strokeStyle = \`oklch(60% 0.16 ${p.hueB} / \${0.28 - Math.abs(i / vCount) * 0.18})\`;
        ctx.beginPath();
        ctx.moveTo(width / 2 + spread * 0.06, horizon);
        ctx.lineTo(width / 2 + spread, height);
        ctx.stroke();
      }
      for (let i = 0; i < 16; i++) {
        const z = ((i / 16 + t) % 1 + 1) % 1;
        const y = horizon + Math.pow(z, 2.4) * (height - horizon);
        ctx.strokeStyle = \`oklch(65% 0.18 ${p.hueA} / \${z * 0.5})\`;
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width, y); ctx.stroke();
      }
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => { cancelAnimationFrame(raf); observer.disconnect(); };
  }, []);

  return <canvas ref={canvasRef} style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }} />;
}
`;
}
