"use client";

import { useEffect, useRef } from "react";
import type { MotionParams } from "../types";

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
}

export function ParticleField({ hueA, hueB, speed, intensity }: MotionParams) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let raf = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);

    function resize() {
      if (!canvas) return;
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    }
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    const count = Math.floor(30 + intensity * 90);
    const linkDist = 110 * dpr;
    const particles: Particle[] = Array.from({ length: count }, () => ({
      x: Math.random() * canvas.width,
      y: Math.random() * canvas.height,
      vx: (Math.random() - 0.5) * 0.4 * speed * dpr,
      vy: (Math.random() - 0.5) * 0.4 * speed * dpr,
    }));

    function frame() {
      if (!canvas || !ctx) return;
      ctx.fillStyle = "oklch(12% 0.01 285)";
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      for (const p of particles) {
        p.x += p.vx;
        p.y += p.vy;
        if (p.x < 0 || p.x > canvas.width) p.vx *= -1;
        if (p.y < 0 || p.y > canvas.height) p.vy *= -1;
      }

      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const a = particles[i];
          const b = particles[j];
          const dx = a.x - b.x;
          const dy = a.y - b.y;
          const dist = Math.hypot(dx, dy);
          if (dist < linkDist) {
            const alpha = (1 - dist / linkDist) * 0.35;
            ctx.strokeStyle = `oklch(65% 0.18 ${hueA} / ${alpha})`;
            ctx.lineWidth = dpr;
            ctx.beginPath();
            ctx.moveTo(a.x, a.y);
            ctx.lineTo(b.x, b.y);
            ctx.stroke();
          }
        }
      }

      for (let i = 0; i < particles.length; i++) {
        const p = particles[i];
        ctx.fillStyle = `oklch(75% 0.15 ${i % 2 ? hueA : hueB})`;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 1.6 * dpr, 0, Math.PI * 2);
        ctx.fill();
      }
      raf = requestAnimationFrame(frame);
    }
    raf = requestAnimationFrame(frame);

    return () => {
      cancelAnimationFrame(raf);
      observer.disconnect();
    };
  }, [hueA, hueB, speed, intensity]);

  return <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" />;
}

export function particleFieldSource(p: MotionParams): string {
  return `"use client";

import { useEffect, useRef } from "react";

/** Particle field background — generated by NOCTURNE Motion Engine. */
export function ParticleFieldBackground() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let raf = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);
    const resize = () => {
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    };
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    const particles = Array.from({ length: ${Math.floor(30 + p.intensity * 90)} }, () => ({
      x: Math.random() * canvas.width,
      y: Math.random() * canvas.height,
      vx: (Math.random() - 0.5) * ${(0.4 * p.speed).toFixed(2)} * dpr,
      vy: (Math.random() - 0.5) * ${(0.4 * p.speed).toFixed(2)} * dpr,
    }));
    const linkDist = 110 * dpr;

    const frame = () => {
      ctx.fillStyle = "oklch(12% 0.01 285)";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      for (const pt of particles) {
        pt.x += pt.vx; pt.y += pt.vy;
        if (pt.x < 0 || pt.x > canvas.width) pt.vx *= -1;
        if (pt.y < 0 || pt.y > canvas.height) pt.vy *= -1;
      }
      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const a = particles[i], b = particles[j];
          const dist = Math.hypot(a.x - b.x, a.y - b.y);
          if (dist < linkDist) {
            ctx.strokeStyle = \`oklch(65% 0.18 ${p.hueA} / \${(1 - dist / linkDist) * 0.35})\`;
            ctx.lineWidth = dpr;
            ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
          }
        }
      }
      particles.forEach((pt, i) => {
        ctx.fillStyle = \`oklch(75% 0.15 \${i % 2 ? ${p.hueA} : ${p.hueB}})\`;
        ctx.beginPath(); ctx.arc(pt.x, pt.y, 1.6 * dpr, 0, Math.PI * 2); ctx.fill();
      });
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => { cancelAnimationFrame(raf); observer.disconnect(); };
  }, []);

  return <canvas ref={canvasRef} style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }} />;
}
`;
}
