"use client";

import { useEffect, useRef } from "react";
import type { MotionParams } from "../types";

export function Waves({ hueA, hueB, speed, intensity }: MotionParams) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let raf = 0;
    let t = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);

    function resize() {
      if (!canvas) return;
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    }
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);

    const lineCount = Math.floor(3 + intensity * 6);

    function frame() {
      if (!canvas || !ctx) return;
      const { width, height } = canvas;
      ctx.fillStyle = "oklch(12% 0.01 285)";
      ctx.fillRect(0, 0, width, height);
      t += 0.008 * speed;

      for (let l = 0; l < lineCount; l++) {
        const progress = l / (lineCount - 1 || 1);
        const hue = hueA + (hueB - hueA) * progress;
        const baseY = height * (0.3 + progress * 0.4);
        const amp = height * 0.08 * (1 + progress);

        ctx.strokeStyle = `oklch(70% 0.19 ${hue} / ${0.5 - progress * 0.25})`;
        ctx.lineWidth = 1.4 * dpr;
        ctx.shadowColor = `oklch(70% 0.19 ${hue} / 0.6)`;
        ctx.shadowBlur = 14 * dpr;
        ctx.beginPath();
        for (let x = 0; x <= width; x += 4 * dpr) {
          const y =
            baseY +
            Math.sin(x * 0.003 + t * (1 + progress * 0.6) + l * 1.4) * amp +
            Math.sin(x * 0.008 - t * 0.7 + l) * amp * 0.3;
          if (x === 0) ctx.moveTo(x, y);
          else ctx.lineTo(x, y);
        }
        ctx.stroke();
      }
      ctx.shadowBlur = 0;
      raf = requestAnimationFrame(frame);
    }
    raf = requestAnimationFrame(frame);

    return () => {
      cancelAnimationFrame(raf);
      observer.disconnect();
    };
  }, [hueA, hueB, speed, intensity]);

  return <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" />;
}

export function wavesSource(p: MotionParams): string {
  return `"use client";

import { useEffect, useRef } from "react";

/** Signal waves background — generated by NOCTURNE Motion Engine. */
export function WavesBackground() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let raf = 0;
    let t = 0;
    const dpr = Math.min(window.devicePixelRatio, 2);
    const resize = () => {
      canvas.width = canvas.offsetWidth * dpr;
      canvas.height = canvas.offsetHeight * dpr;
    };
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);
    const lineCount = ${Math.floor(3 + p.intensity * 6)};

    const frame = () => {
      const { width, height } = canvas;
      ctx.fillStyle = "oklch(12% 0.01 285)";
      ctx.fillRect(0, 0, width, height);
      t += ${(0.008 * p.speed).toFixed(4)};
      for (let l = 0; l < lineCount; l++) {
        const progress = l / (lineCount - 1 || 1);
        const hue = ${p.hueA} + (${p.hueB} - ${p.hueA}) * progress;
        const baseY = height * (0.3 + progress * 0.4);
        const amp = height * 0.08 * (1 + progress);
        ctx.strokeStyle = \`oklch(70% 0.19 \${hue} / \${0.5 - progress * 0.25})\`;
        ctx.lineWidth = 1.4 * dpr;
        ctx.shadowColor = \`oklch(70% 0.19 \${hue} / 0.6)\`;
        ctx.shadowBlur = 14 * dpr;
        ctx.beginPath();
        for (let x = 0; x <= width; x += 4 * dpr) {
          const y = baseY + Math.sin(x * 0.003 + t * (1 + progress * 0.6) + l * 1.4) * amp + Math.sin(x * 0.008 - t * 0.7 + l) * amp * 0.3;
          if (x === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
        }
        ctx.stroke();
      }
      ctx.shadowBlur = 0;
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => { cancelAnimationFrame(raf); observer.disconnect(); };
  }, []);

  return <canvas ref={canvasRef} style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }} />;
}
`;
}
